version: "3.3"
services:            
    playlist:
        environment:
            USERSERVICE_HOST: userservice
        image: playlist
        depends_on:
            - userservice
        networks:
            - microservices
        ports:
            - 8080:8080

    userservice:
        image: userservice
        networks:
            - microservices




networks:
    microservices:
