version: "3.3"
services:

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
    python_scripts:
        image: python:3.8
        volumes:
            - ./create_database.py:/initialDatabaseScript/create_database.py
        command: /bin/sh -c "pip install mysql-connector-python && pip install --upgrade google-api-python-client && pip install pandas && pip install google-cloud-storage && python /initialDatabaseScript/create_database.py"
        depends_on:
            - db
    playlist:
        environment:
            USERSERVICE_HOST: userservice
        image: playlist
        depends_on:
            - userservice
        networks:
            - microservices
        ports:
            - 8080:8080

    userservice:
        image: userservice
        depends_on:
            - python_scripts
        networks:
            - microservices

    songcomments:
        environment:
            COMMENTS_HOST: songservice
        image: songcomments
        depends_on:
            - songservice
        networks:
            - microservices
        ports:
            - 5000:5000

    songservice:
        image: songservice
        depends_on:
            - python_scripts
        networks:
            - microservices

    allcontentservice:
        image: allcontentservice
        depends_on:
            - python_scripts
        networks:
            - microservices
    
    topchartsservice:
        image: topchartsservice
        environment:
            TOPCHARTS_HOST: allcontentservice
        depends_on:
            - allcontentservice
        networks:
            - microservices
        ports:
            - 5001:5001

    searchservice:
        image: searchservice
        environment:
            SEARCH_HOST: songservice
        depends_on:
            - songservice
        networks:
            - microservices
        ports:
            - 5002:5002
    
    songdetailsservice:
        image: songdetailsservice
        environment:
            SONGDETAILS_HOST: songservice
        depends_on:
            - songservice
        networks:
            - microservices
        ports:
            - 5003:5003

networks:
    microservices:
