version: "3.3"
services:

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
    python_scripts:
        image: python:3.8
        volumes:
            - ./create_database.py:/initialDatabaseScript/create_database.py
        command: /bin/sh -c "pip install mysql-connector-python && pip install --upgrade google-api-python-client && pip install pandas && pip install google-cloud-storage && python /initialDatabaseScript/create_database.py"
        depends_on:
            - db    
    # database_creator:
    #     image: python:3.8
    #     command: python create_database.py
    #     depends_on:
    #         - db
    # playlist:
    #     environment:
    #         USERSERVICE_HOST: userservice
    #     # DOCKER_BUILDKIT=1 docker build . -f marketplace/Dockerfile \
    #     #                   -t marketplace --secret id=ca.key,src=ca.key
    #     image: playlist
    #     networks:
    #         - microservices
    #     ports:
    #         - 8080:8080

    # userservice:
    #     # DOCKER_BUILDKIT=1 docker build . -f recommendations/Dockerfile \
    #     #                   -t recommendations --secret id=ca.key,src=ca.key
    #     image: userservice
    #     networks:
    #         - microservices

    # songcomments:
    #     environment:
    #         COMMENTS_HOST: songservice
    #     # DOCKER_BUILDKIT=1 docker build . -f marketplace/Dockerfile \
    #     #                   -t marketplace --secret id=ca.key,src=ca.key
    #     image: songcomments
    #     networks:
    #         - microservices
    #     ports:
    #         - 5000:5000

    # songservice:
    #     # DOCKER_BUILDKIT=1 docker build . -f recommendations/Dockerfile \
    #     #                   -t recommendations --secret id=ca.key,src=ca.key
    #     image: songservice
    #     networks:
    #         - microservices
networks:
    microservices:
