version: "3.3"
services:            
    playlist:
        environment:
            USERSERVICE_HOST: userservice
        image: playlist
        depends_on:
            - su2001/userservice:test
        networks:
            - microservices
        ports:
            - 8080:8080

    userservice:
        image: su2001/userservice
        networks:
            - microservices




networks:
    microservices:
