version: "3.3"
services:

    playlist:
        environment:
            USERSERVICE_HOST: userservice
        # DOCKER_BUILDKIT=1 docker build . -f marketplace/Dockerfile \
        #                   -t marketplace --secret id=ca.key,src=ca.key
        image: playlist
        networks:
            - microservices
        ports:
            - 8080:8080

    userservice:
        # DOCKER_BUILDKIT=1 docker build . -f recommendations/Dockerfile \
        #                   -t recommendations --secret id=ca.key,src=ca.key
        image: userservice
        networks:
            - microservices

    songcomments:
        environment:
            COMMENTS_HOST: songservice
        # DOCKER_BUILDKIT=1 docker build . -f marketplace/Dockerfile \
        #                   -t marketplace --secret id=ca.key,src=ca.key
        image: songcomments
        networks:
            - microservices
        ports:
            - 5000:5000

    songservice:
        # DOCKER_BUILDKIT=1 docker build . -f recommendations/Dockerfile \
        #                   -t recommendations --secret id=ca.key,src=ca.key
        image: songservice
        networks:
            - microservices

networks:
    microservices:
