# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\"2\n\x04Song\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x61rtists\x18\x03 \x01(\t\"$\n\x10GetSearchRequest\x12\x10\n\x08songname\x18\x01 \x01(\t\")\n\x11GetSearchResponse\x12\x14\n\x05songs\x18\x01 \x03(\x0b\x32\x05.Song2<\n\x06Search\x12\x32\n\tGetSearch\x12\x11.GetSearchRequest\x1a\x12.GetSearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SONG']._serialized_start=16
  _globals['_SONG']._serialized_end=66
  _globals['_GETSEARCHREQUEST']._serialized_start=68
  _globals['_GETSEARCHREQUEST']._serialized_end=104
  _globals['_GETSEARCHRESPONSE']._serialized_start=106
  _globals['_GETSEARCHRESPONSE']._serialized_end=147
  _globals['_SEARCH']._serialized_start=149
  _globals['_SEARCH']._serialized_end=209
# @@protoc_insertion_point(module_scope)
