# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playlist.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eplaylist.proto\"6\n\x12\x41\x64\x64PlayListRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07song_id\x18\x02 \x01(\x05\"\'\n\x13\x41\x64\x64PlayListResponse\x12\x10\n\x08response\x18\x01 \x01(\x05\"9\n\x15RemovePlayListRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07song_id\x18\x02 \x01(\x05\"*\n\x16RemovePlayListResponse\x12\x10\n\x08response\x18\x01 \x01(\x05\"%\n\x12GetPlayListRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"$\n\x13GetPlayListResponse\x12\r\n\x05songs\x18\x01 \x03(\x05\x32?\n\x0b\x41\x64\x64PlayList\x12\x30\n\x03\x41\x64\x64\x12\x13.AddPlayListRequest\x1a\x14.AddPlayListResponse2K\n\x0eRemovePlayList\x12\x39\n\x06Remove\x12\x16.RemovePlayListRequest\x1a\x17.RemovePlayListResponse2?\n\x0bGetPlayList\x12\x30\n\x03Get\x12\x13.GetPlayListRequest\x1a\x14.GetPlayListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'playlist_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDPLAYLISTREQUEST']._serialized_start=18
  _globals['_ADDPLAYLISTREQUEST']._serialized_end=72
  _globals['_ADDPLAYLISTRESPONSE']._serialized_start=74
  _globals['_ADDPLAYLISTRESPONSE']._serialized_end=113
  _globals['_REMOVEPLAYLISTREQUEST']._serialized_start=115
  _globals['_REMOVEPLAYLISTREQUEST']._serialized_end=172
  _globals['_REMOVEPLAYLISTRESPONSE']._serialized_start=174
  _globals['_REMOVEPLAYLISTRESPONSE']._serialized_end=216
  _globals['_GETPLAYLISTREQUEST']._serialized_start=218
  _globals['_GETPLAYLISTREQUEST']._serialized_end=255
  _globals['_GETPLAYLISTRESPONSE']._serialized_start=257
  _globals['_GETPLAYLISTRESPONSE']._serialized_end=293
  _globals['_ADDPLAYLIST']._serialized_start=295
  _globals['_ADDPLAYLIST']._serialized_end=358
  _globals['_REMOVEPLAYLIST']._serialized_start=360
  _globals['_REMOVEPLAYLIST']._serialized_end=435
  _globals['_GETPLAYLIST']._serialized_start=437
  _globals['_GETPLAYLIST']._serialized_end=500
# @@protoc_insertion_point(module_scope)
