apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-d
  labels:
    app: playlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playlist
  template:
    metadata:
      labels:
        app: playlist
    spec:
      containers:
      - name: playlist
        image: su2001/playlist
        ports:
          - containerPort: 8080
        env:
          - name: USERSERVICE_HOST
            value: "userservice-service"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 60
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: playlist-service
  labels:
    app: playlist
spec:
  type: ClusterIP
  selector:
    app: playlist
  ports:
    - name: http
      protocol: TCP
      port: 80
      #nodePort: 30000
      targetPort: 8080

