apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-d
  labels:
    app: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: su2001/userservice
        ports:
          - containerPort: 50051
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: userservice-service
  labels:
    app: userservice
spec:
  type: ClusterIP

  selector:
    app: userservice
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051

