apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  labels:
    app: userservice
spec:
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: su2001/userservice
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
          - containerPort: 50051
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 30
        env:
          - name: AUTH_JSON
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: auth
---
apiVersion: v1
kind: Service
metadata:
  name: userservice-service
  labels:
    app: userservice
spec:
  type: ClusterIP

  selector:
    app: userservice
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
---
apiVersion: autoscaling/v1 
kind: HorizontalPodAutoscaler 
metadata:
  name: userservice-scalability-control
spec:
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: userservice
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

