apiVersion: autoscaling/v1 
kind: HorizontalPodAutoscaler 
metadata:
  name: scalability-control
spec:
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: scalability-control
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50