apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spotify-ingress
  annotations:

    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
    # If the class annotation is not specified it defaults to "gce".
    
spec:
  rules:
  - http:
      paths:
      - path: /premium/song-details/
        pathType: Prefix
        backend:
          service:
            name: songcomments-service
            port:
              number: 5000
      - path: /premium/playlist
        pathType: Prefix
        backend:
          service:
            name: playlist-service
            port:
              number: 8080    
      - path: /regular/song-details/
        pathType: Prefix
        backend:
          service:
            name: songdetails-service
            port:
              number: 5003 
      - path: /regular/search
        pathType: Prefix
        backend:
          service:
            name: searchservice-service
            port:
              number: 5002
      - path: /regular/top-charts
        pathType: Prefix
        backend:
          service:
            name: topcharts-service
            port:
              number: 5001
