apiVersion: monitoring.googleapis.com/v1
king: PodMonitoring
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  selector:
    matchlabels:
      app: node-exporter
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s