# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playlist.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eplaylist.proto\"9\n\x15ModifyPlayListRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07song_id\x18\x02 \x01(\x05\"$\n\x10PlayListResponse\x12\x10\n\x08response\x18\x01 \x01(\x05\"%\n\x12GetPlayListRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"6\n\x13GetPlayListResponse\x12\x10\n\x08response\x18\x01 \x01(\x05\x12\r\n\x05songs\x18\x02 \x03(\x05\x32\xaa\x01\n\x0fPlayListService\x12\x30\n\x03\x41\x64\x64\x12\x16.ModifyPlayListRequest\x1a\x11.PlayListResponse\x12\x33\n\x06Remove\x12\x16.ModifyPlayListRequest\x1a\x11.PlayListResponse\x12\x30\n\x03Get\x12\x13.GetPlayListRequest\x1a\x14.GetPlayListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'playlist_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MODIFYPLAYLISTREQUEST']._serialized_start=18
  _globals['_MODIFYPLAYLISTREQUEST']._serialized_end=75
  _globals['_PLAYLISTRESPONSE']._serialized_start=77
  _globals['_PLAYLISTRESPONSE']._serialized_end=113
  _globals['_GETPLAYLISTREQUEST']._serialized_start=115
  _globals['_GETPLAYLISTREQUEST']._serialized_end=152
  _globals['_GETPLAYLISTRESPONSE']._serialized_start=154
  _globals['_GETPLAYLISTRESPONSE']._serialized_end=208
  _globals['_PLAYLISTSERVICE']._serialized_start=211
  _globals['_PLAYLISTSERVICE']._serialized_end=381
# @@protoc_insertion_point(module_scope)
