apiVersion: apps/v1
kind: Deployment
metadata:
  name: allcontentservice
  labels:
    app: allcontentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allcontentservice
  template:
    metadata:
      labels:
        app: allcontentservice
    spec:
      containers:
      - name: allcontentservice
        image: su2001/allcontentservice
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
          - containerPort: 50051
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: allcontentservice-service
  labels:
    app: allcontentservice
spec:
  type: ClusterIP

  selector:
    app: allcontentservice
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
---
apiVersion: autoscaling/v1 
kind: HorizontalPodAutoscaler 
metadata:
  name: allcontentservice-scalability-control
spec:
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: allcontentservice
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

