apiVersion: apps/v1
kind: Deployment
metadata:
  name: allcontentservice-d
  labels:
    app: allcontentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allcontentservice
  template:
    metadata:
      labels:
        app: allcontentservice
    spec:
      containers:
      - name: allcontentservice
        image: su2001/allcontentservice
        ports:
          - containerPort: 50051
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: allcontentservice-service
  labels:
    app: allcontentservice
spec:
  type: ClusterIP

  selector:
    app: allcontentservice
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051

