apiVersion: apps/v1
kind: Deployment
metadata:
  name: topcharts-d
  labels:
    app: topcharts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topcharts
  template:
    metadata:
      labels:
        app: topcharts
    spec:
      containers:
      - name: topchartsservice
        image: su2001/topchartsservice
        ports:
        - containerPort: 5001
        env:
        - name: TOPCHARTS_HOST
          value: "allcontentservice-service"
---
apiVersion: v1
kind: Service
metadata:
  name: topcharts-service
  labels:
    app: topcharts
spec:
  type: NodePort
  selector:
    app: topcharts
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30001
      targetPort: 5001