apiVersion: apps/v1
kind: Deployment
metadata:
  name: topcharts
  labels:
    app: topcharts
spec:
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: topcharts
  template:
    metadata:
      labels:
        app: topcharts
    spec:
      containers:
      - name: topchartsservice
        image: su2001/topchartsservice
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 5001
        env:
        - name: TOPCHARTS_HOST
          value: "allcontentservice-service"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 60
        readinessProbe:
          tcpSocket:
            port: 5001
          initialDelaySeconds: 20
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: topcharts-service
  labels:
    app: topcharts
spec:
  type: LoadBalancer
  selector:
    app: topcharts
  ports:
    - name: http
      protocol: TCP
      port: 80
      #nodePort: 30001
      targetPort: 5001
---
apiVersion: autoscaling/v1 
kind: HorizontalPodAutoscaler 
metadata:
  name: topcharts-scalability-control
spec:
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: topcharts
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
