name: CI & CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-deploy:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest

    steps:
    ## CI ##
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest

    ## CD ##
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESSTOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: topCharts
        file: topCharts/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/topchartsservice:latest

    # Uncomment the following steps if you want to deploy to Kubernetes
    # - name: Set up kubectl
    #   uses: azure/setup-kubectl@v1
    #   with:
    #     version: 'latest'

    # - name: Deploy to Kubernetes
    #   env:
    #     KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
    #   run: |
    #     echo "$KUBE_CONFIG_DATA" | base64 --decode > $HOME/.kube/config
    #     kubectl apply -f deployment.yaml
