name: CI & CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-deploy:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest

    steps:

    ## CI ##
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Run tests in topCharts
      run: |
        cd topCharts
        if [ -f requirements.txt ]; then
          pip3 install -r requirements.txt
        fi
        pytest
      shell: bash

    ## CD ##
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESSTOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: topCharts
        file: topCharts/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/topchartsservice:latest
