apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchservice
  labels:
    app: searchservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searchservice
  template:
    metadata:
      labels:
        app: searchservice
    spec:
      containers:
      - name: searchservice
        image: su2001/searchservice
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
          - containerPort: 5002
        env:
          - name: SEARCH_HOST
            value: "songservice-service"
        livenessProbe:
          httpGet:
            path: /
            port: 5002
          initialDelaySeconds: 15
          periodSeconds: 60
        readinessProbe:
          tcpSocket:
            port: 5002
          initialDelaySeconds: 20
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: searchservice-service
  labels:
    app: searchservice
spec:
  type: LoadBalancer
  selector:
    app: searchservice
  ports:
    - name: http
      protocol: TCP
      port: 80
      #nodePort: 30002
      targetPort: 5002
---
apiVersion: autoscaling/v1 
kind: HorizontalPodAutoscaler 
metadata:
  name: searchservice-scalability-control
spec:
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: searchservice
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50


