apiVersion: apps/v1
kind: Deployment
metadata:
  name: songcomments
  labels:
    app: songcomments
spec:
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: songcomments
  template:
    metadata:
      labels:
        app: songcomments
    spec:
      containers:
      - name: songcomments
        image: su2001/songcomments
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
          - containerPort: 5000
        env:
          - name: COMMENTS_HOST
            value: "songservice-service"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: songcomments-service
  labels:
    app: songcomments
spec:
  type: ClusterIP
  selector:
    app: songcomments
  ports:
    - name: http
      protocol: TCP
      port: 5000
      #nodePort: 30003
      targetPort: 5000
---
apiVersion: autoscaling/v1 
kind: HorizontalPodAutoscaler 
metadata:
  name: songcomments-scalability-control
spec:
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: songcomments
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
