apiVersion: apps/v1
kind: Deployment
metadata:
  name: songdetails-d
  labels:
    app: songdetails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: songdetails
  template:
    metadata:
      labels:
        app: songdetails
    spec:
      containers:
      - name: songdetailsservice
        image: su2001/songdetailsservice
        ports:
        - containerPort: 5003
        env:
        - name: SONGDETAILS_HOST
          value: "songservice-service"
---
apiVersion: v1
kind: Service
metadata:
  name: songdetails-service
  labels:
    app: songdetails
spec:
  type: NodePort
  selector:
    app: songdetails
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30004
      targetPort: 5003