apiVersion: apps/v1
kind: Deployment
metadata:
  name: songdetails
  labels:
    app: songdetails
spec:
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: songdetails
  template:
    metadata:
      labels:
        app: songdetails
    spec:
      containers:
      - name: songdetailsservice
        image: su2001/songdetailsservice
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 5003
        env:
        - name: SONGDETAILS_HOST
          value: "songservice-service"
        livenessProbe:
          httpGet:
            path: /
            port: 5003
          initialDelaySeconds: 15
          periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: songdetails-service
  labels:
    app: songdetails
spec:
  type: ClusterIP
  selector:
    app: songdetails
  ports:
    - name: http
      protocol: TCP
      port: 80
      #nodePort: 30004
      targetPort: 5003
---
apiVersion: autoscaling/v1 
kind: HorizontalPodAutoscaler 
metadata:
  name: songdetails-scalability-control
spec:
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: songdetails
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
