apiVersion: apps/v1
kind: Deployment
metadata:
  name: songservice
  labels:
    app: songservice
spec:
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: songservice
  template:
    metadata:
      labels:
        app: songservice
    spec:
      containers:
      - name: songservice
        image: su2001/songservice
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
          - containerPort: 50051
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: songservice-service
  labels:
    app: songservice
spec:
  type: ClusterIP

  selector:
    app: songservice
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
---
apiVersion: autoscaling/v1 
kind: HorizontalPodAutoscaler 
metadata:
  name: songservice-scalability-control
spec:
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: songservice
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

