apiVersion: apps/v1
kind: Deployment
metadata:
  name: songcomments-d
  labels:
    app: songcomments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: songcomments
  template:
    metadata:
      labels:
        app: songcomments
    spec:
      containers:
      - name: songcomments
        image: su2001/songcomments
        ports:
          - containerPort: 5000
        env:
          - name: COMMENTS_HOST
            value: "songservice-service"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 60
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: songcomments-service
  labels:
    app: songcomments
spec:
  type: ClusterIP
  selector:
    app: songcomments
  ports:
    - name: http
      protocol: TCP
      port: 80
      #nodePort: 30003
      targetPort: 5000